### ISSUE TITLE
Connecting to YouTrack fails

### ISSUE THREAD

**Issue by knippers** [cleobis/youtrack-outlook-addin#2]
From a Office 365 Outlook to a standalone YouTrack with up-to-par SSL certificate the connection fails with a ssl/tls issue, this is captured in the inner exception. 

The fix is to add the following in ThisAddin_Startup:

ServicePointManager.Expect100Continue = true;
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

**Comment by cleobis** [comment]
Thanks. Updated ThisAddIn_Startup:
```
// Fix for failed SSL/TLS connection. See https://stackoverflow.com/a/71320604.
AppContext.SetSwitch("Switch.System.ServiceModel.DisableUsingServicePointManagerSecurityProtocols", false);
AppContext.SetSwitch("Switch.System.Net.DontEnableSchUseStrongCrypto", false);
```
